// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITests
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Svi parametri uneseni
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WinComboBox uIKomComboBox = this.UILufthansaRezervacijaWindow.UIPolazisteCBWindow.UIKomComboBox;
            WinButton uIOpenButton = this.UILufthansaRezervacijaWindow.UIOdredisteCBWindow.UIOpenButton;
            WinComboBox uIOdredisteCBComboBox = this.UILufthansaRezervacijaWindow.UIOdredisteCBWindow.UIOdredisteCBComboBox;
            WinEdit uIPrtljagTxtEdit = this.UILufthansaRezervacijaWindow.UIPrtljagTxtWindow.UIPrtljagTxtEdit;
            WinEdit uITakseTxtEdit = this.UILufthansaRezervacijaWindow.UITakseTxtWindow.UITakseTxtEdit;
            WinSlider uIKlasaBarSlider = this.UILufthansaRezervacijaWindow.UIKlasaBarWindow.UIKlasaBarSlider;
            WinButton uIIzračunajcijenuletaButton = this.UILufthansaRezervacijaWindow.UIIzračunajcijenuletaWindow.UIIzračunajcijenuletaButton;
            WinEdit uIImeTxtEdit = this.UILufthansaRezervacijaWindow.UIImeTxtWindow.UIImeTxtEdit;
            WinEdit uIPrezimeTxtEdit = this.UILufthansaRezervacijaWindow.UIPrezimeTxtWindow.UIPrezimeTxtEdit;
            WinEdit uIJmbgTxtEdit = this.UILufthansaRezervacijaWindow.UIJmbgTxtWindow.UIJmbgTxtEdit;
            WinEdit uITelefonTxtEdit = this.UILufthansaRezervacijaWindow.UITelefonTxtWindow.UITelefonTxtEdit;
            WinEdit uIKomentarTxtEdit = this.UILufthansaRezervacijaWindow.UIKomentarTxtWindow.UIKomentarTxtEdit;
            WinButton uIRezervišiletButton = this.UILufthansaRezervacijaWindow.UIRezervišiletWindow.UIRezervišiletButton;
            #endregion

            // Last mouse action was not recorded.

            // Select 'Sarajevo' in 'kom' combo box
            uIKomComboBox.SelectedItem = this.RecordedMethod1Params.UIKomComboBoxSelectedItem;

            // Click 'Open' button
            Mouse.Click(uIOpenButton, new Point(7, 3));

            // Last mouse action was not recorded.

            // Select 'Istanbul' in 'odredisteCB' combo box
            uIOdredisteCBComboBox.SelectedItem = this.RecordedMethod1Params.UIOdredisteCBComboBoxSelectedItem;

            // Type '2' in 'prtljagTxt' text box
            uIPrtljagTxtEdit.Text = this.RecordedMethod1Params.UIPrtljagTxtEditText;

            // Type '{Tab}' in 'prtljagTxt' text box
            Keyboard.SendKeys(uIPrtljagTxtEdit, this.RecordedMethod1Params.UIPrtljagTxtEditSendKeys, ModifierKeys.None);

            // Type '50' in 'takseTxt' text box
            uITakseTxtEdit.Text = this.RecordedMethod1Params.UITakseTxtEditText;

            // Set position '5' in 'klasaBar' slider
            uIKlasaBarSlider.PositionAsString = this.RecordedMethod1Params.UIKlasaBarSliderPositionAsString;

            // Click 'Izračunaj cijenu leta' button
            Mouse.Click(uIIzračunajcijenuletaButton, new Point(196, 25));

            // Type 'Imenko' in 'imeTxt' text box
            uIImeTxtEdit.Text = this.RecordedMethod1Params.UIImeTxtEditText;

            // Type '{Tab}' in 'imeTxt' text box
            Keyboard.SendKeys(uIImeTxtEdit, this.RecordedMethod1Params.UIImeTxtEditSendKeys, ModifierKeys.None);

            // Type 'Prezimenko' in 'prezimeTxt' text box
            uIPrezimeTxtEdit.Text = this.RecordedMethod1Params.UIPrezimeTxtEditText;

            // Type '{Tab}' in 'prezimeTxt' text box
            Keyboard.SendKeys(uIPrezimeTxtEdit, this.RecordedMethod1Params.UIPrezimeTxtEditSendKeys, ModifierKeys.None);

            // Type '0123456789123' in 'jmbgTxt' text box
            uIJmbgTxtEdit.Text = this.RecordedMethod1Params.UIJmbgTxtEditText;

            // Type '{Tab}' in 'jmbgTxt' text box
            Keyboard.SendKeys(uIJmbgTxtEdit, this.RecordedMethod1Params.UIJmbgTxtEditSendKeys, ModifierKeys.None);

            // Type '38761123456' in 'telefonTxt' text box
            uITelefonTxtEdit.Text = this.RecordedMethod1Params.UITelefonTxtEditText;

            // Type '{Tab}' in 'telefonTxt' text box
            Keyboard.SendKeys(uITelefonTxtEdit, this.RecordedMethod1Params.UITelefonTxtEditSendKeys, ModifierKeys.None);

            // Type 'komentar' in 'komentarTxt' text box
            uIKomentarTxtEdit.Text = this.RecordedMethod1Params.UIKomentarTxtEditText;

            // Click 'Rezerviši let' button
            Mouse.Click(uIRezervišiletButton, new Point(53, 27));
        }
        
        /// <summary>
        /// SviParametriUneseniTest - Use 'SviParametriUneseniTestExpectedValues' to pass parameters into this method.
        /// </summary>
        public void SviParametriUneseniTest()
        {
            #region Variable Declarations
            WinEdit uIDistancaTxtEdit = this.UILufthansaRezervacijaWindow.UIDistancaTxtWindow.UIDistancaTxtEdit;
            WinEdit uIPrtljagTxtEdit = this.UILufthansaRezervacijaWindow.UIPrtljagTxtWindow.UIPrtljagTxtEdit;
            WinEdit uITakseTxtEdit = this.UILufthansaRezervacijaWindow.UITakseTxtWindow.UITakseTxtEdit;
            WinEdit uICijenaTxtEdit = this.UILufthansaRezervacijaWindow.UICijenaTxtWindow.UICijenaTxtEdit;
            WinEdit uIImeTxtEdit = this.UILufthansaRezervacijaWindow.UIImeTxtWindow.UIImeTxtEdit;
            WinEdit uIPrezimeTxtEdit = this.UILufthansaRezervacijaWindow.UIPrezimeTxtWindow.UIPrezimeTxtEdit;
            WinEdit uIJmbgTxtEdit = this.UILufthansaRezervacijaWindow.UIJmbgTxtWindow.UIJmbgTxtEdit;
            WinEdit uITelefonTxtEdit = this.UILufthansaRezervacijaWindow.UITelefonTxtWindow.UITelefonTxtEdit;
            #endregion

            // Verify that the 'Text' property of 'distancaTxt' text box is not equal to '0'
            Assert.AreNotEqual(this.SviParametriUneseniTestExpectedValues.UIDistancaTxtEditText, uIDistancaTxtEdit.Text, "Unesite distancu!");

            // Verify that the 'Text' property of 'prtljagTxt' text box is not equal to ''
            Assert.AreNotEqual(this.SviParametriUneseniTestExpectedValues.UIPrtljagTxtEditText, uIPrtljagTxtEdit.Text, "Unesite prtljag!");

            // Verify that the 'Text' property of 'takseTxt' text box is not equal to ''
            Assert.AreNotEqual(this.SviParametriUneseniTestExpectedValues.UITakseTxtEditText, uITakseTxtEdit.Text, "Unesite takse!");

            // Verify that the 'Text' property of 'cijenaTxt' text box is not equal to ''
            Assert.AreNotEqual(this.SviParametriUneseniTestExpectedValues.UICijenaTxtEditText, uICijenaTxtEdit.Text, "Cijena leta nije unesena!");

            // Verify that the 'Text' property of 'imeTxt' text box is not equal to ''
            Assert.AreNotEqual(this.SviParametriUneseniTestExpectedValues.UIImeTxtEditText, uIImeTxtEdit.Text, "Ime putnika nije uneseno!");

            // Verify that the 'Text' property of 'prezimeTxt' text box is not equal to ''
            Assert.AreNotEqual(this.SviParametriUneseniTestExpectedValues.UIPrezimeTxtEditText, uIPrezimeTxtEdit.Text, "Prezime putnika nije uneseno!");

            // Verify that the 'Text' property of 'jmbgTxt' text box is not equal to ''
            Assert.AreNotEqual(this.SviParametriUneseniTestExpectedValues.UIJmbgTxtEditText, uIJmbgTxtEdit.Text, "JMBG putnika nije unesen!");

            // Verify that the 'Text' property of 'telefonTxt' text box is not equal to ''
            Assert.AreNotEqual(this.SviParametriUneseniTestExpectedValues.UITelefonTxtEditText, uITelefonTxtEdit.Text, "Telefon putnika nije unesen!");
        }
        
        /// <summary>
        /// PrtljagNijeUnesen - Use 'PrtljagNijeUnesenParams' to pass parameters into this method.
        /// </summary>
        public void PrtljagNijeUnesen()
        {
            #region Variable Declarations
            WinComboBox uIKomComboBox = this.UILufthansaRezervacijaWindow.UIPolazisteCBWindow.UIKomComboBox;
            WinComboBox uIOdredisteCBComboBox = this.UILufthansaRezervacijaWindow.UIOdredisteCBWindow.UIOdredisteCBComboBox;
            WinEdit uIPrtljagTxtEdit = this.UILufthansaRezervacijaWindow.UIPrtljagTxtWindow.UIPrtljagTxtEdit;
            WinEdit uITakseTxtEdit = this.UILufthansaRezervacijaWindow.UITakseTxtWindow.UITakseTxtEdit;
            WinSlider uIKlasaBarSlider = this.UILufthansaRezervacijaWindow.UIKlasaBarWindow.UIKlasaBarSlider;
            WinButton uIIzračunajcijenuletaButton = this.UILufthansaRezervacijaWindow.UIIzračunajcijenuletaWindow.UIIzračunajcijenuletaButton;
            WinEdit uIImeTxtEdit = this.UILufthansaRezervacijaWindow.UIImeTxtWindow.UIImeTxtEdit;
            WinEdit uIPrezimeTxtEdit = this.UILufthansaRezervacijaWindow.UIPrezimeTxtWindow.UIPrezimeTxtEdit;
            WinEdit uIJmbgTxtEdit = this.UILufthansaRezervacijaWindow.UIJmbgTxtWindow.UIJmbgTxtEdit;
            WinEdit uITelefonTxtEdit = this.UILufthansaRezervacijaWindow.UITelefonTxtWindow.UITelefonTxtEdit;
            WinEdit uIKomentarTxtEdit = this.UILufthansaRezervacijaWindow.UIKomentarTxtWindow.UIKomentarTxtEdit;
            WinButton uIRezervišiletButton = this.UILufthansaRezervacijaWindow.UIRezervišiletWindow.UIRezervišiletButton;
            #endregion

            // Last mouse action was not recorded.

            // Select 'Istanbul' in 'kom' combo box
            uIKomComboBox.SelectedItem = this.PrtljagNijeUnesenParams.UIKomComboBoxSelectedItem;

            // Select 'Sarajevo' in 'odredisteCB' combo box
            uIOdredisteCBComboBox.SelectedItem = this.PrtljagNijeUnesenParams.UIOdredisteCBComboBoxSelectedItem;

            // Type '5' in 'prtljagTxt' text box
            uIPrtljagTxtEdit.Text = this.PrtljagNijeUnesenParams.UIPrtljagTxtEditText;

            // Type '70' in 'takseTxt' text box
            uITakseTxtEdit.Text = this.PrtljagNijeUnesenParams.UITakseTxtEditText;

            // Set position '9' in 'klasaBar' slider
            uIKlasaBarSlider.PositionAsString = this.PrtljagNijeUnesenParams.UIKlasaBarSliderPositionAsString;

            // Click 'Izračunaj cijenu leta' button
            Mouse.Click(uIIzračunajcijenuletaButton, new Point(192, 7));

            // Type 'Reufik' in 'imeTxt' text box
            uIImeTxtEdit.Text = this.PrtljagNijeUnesenParams.UIImeTxtEditText;

            // Type '{Tab}' in 'imeTxt' text box
            Keyboard.SendKeys(uIImeTxtEdit, this.PrtljagNijeUnesenParams.UIImeTxtEditSendKeys, ModifierKeys.None);

            // Type 'Mujkic' in 'prezimeTxt' text box
            uIPrezimeTxtEdit.Text = this.PrtljagNijeUnesenParams.UIPrezimeTxtEditText;

            // Type '{Tab}' in 'prezimeTxt' text box
            Keyboard.SendKeys(uIPrezimeTxtEdit, this.PrtljagNijeUnesenParams.UIPrezimeTxtEditSendKeys, ModifierKeys.None);

            // Type '1203975012310' in 'jmbgTxt' text box
            uIJmbgTxtEdit.Text = this.PrtljagNijeUnesenParams.UIJmbgTxtEditText;

            // Type '{Tab}' in 'jmbgTxt' text box
            Keyboard.SendKeys(uIJmbgTxtEdit, this.PrtljagNijeUnesenParams.UIJmbgTxtEditSendKeys, ModifierKeys.None);

            // Type '38761111222' in 'telefonTxt' text box
            uITelefonTxtEdit.Text = this.PrtljagNijeUnesenParams.UITelefonTxtEditText;

            // Type 'Refko' in 'komentarTxt' text box
            uIKomentarTxtEdit.Text = this.PrtljagNijeUnesenParams.UIKomentarTxtEditText;

            // Type '' in 'prtljagTxt' text box
            uIPrtljagTxtEdit.Text = this.PrtljagNijeUnesenParams.UIPrtljagTxtEditText1;

            // Click 'Rezerviši let' button
            Mouse.Click(uIRezervišiletButton, new Point(225, 10));
        }
        
        /// <summary>
        /// Svi parametri za let uneseni, osim takse koja se računa klikom na dugme "Izračunaj cijenu leta"
        /// </summary>
        public void RacunanjeTakse()
        {
            #region Variable Declarations
            WinComboBox uIKomComboBox = this.UILufthansaRezervacijaWindow.UIPolazisteCBWindow.UIKomComboBox;
            WinComboBox uIOdredisteCBComboBox = this.UILufthansaRezervacijaWindow.UIOdredisteCBWindow.UIOdredisteCBComboBox;
            WinEdit uIPrtljagTxtEdit = this.UILufthansaRezervacijaWindow.UIPrtljagTxtWindow.UIPrtljagTxtEdit;
            WinEdit uICijenaTxtEdit = this.UILufthansaRezervacijaWindow.UICijenaTxtWindow.UICijenaTxtEdit;
            WinSlider uIKlasaBarSlider = this.UILufthansaRezervacijaWindow.UIKlasaBarWindow.UIKlasaBarSlider;
            WinButton uIIzračunajcijenuletaButton = this.UILufthansaRezervacijaWindow.UIIzračunajcijenuletaWindow.UIIzračunajcijenuletaButton;
            #endregion

            // Last mouse action was not recorded.

            // Select 'Sarajevo' in 'kom' combo box
            uIKomComboBox.SelectedItem = this.RacunanjeTakseParams.UIKomComboBoxSelectedItem;

            // Click 'odredisteCB' combo box
            Mouse.Click(uIOdredisteCBComboBox, new Point(31, 6));

            // Last mouse action was not recorded.

            // Last mouse action was not recorded.

            // Select 'Pariz' in 'odredisteCB' combo box
            uIOdredisteCBComboBox.SelectedItem = this.RacunanjeTakseParams.UIOdredisteCBComboBoxSelectedItem;

            // Type '2' in 'prtljagTxt' text box
            uIPrtljagTxtEdit.Text = this.RacunanjeTakseParams.UIPrtljagTxtEditText;

            // Type '250' in 'cijenaTxt' text box
            uICijenaTxtEdit.Text = this.RacunanjeTakseParams.UICijenaTxtEditText;

            // Set position '5' in 'klasaBar' slider
            uIKlasaBarSlider.PositionAsString = this.RacunanjeTakseParams.UIKlasaBarSliderPositionAsString;

            // Click 'Izračunaj cijenu leta' button
            Mouse.Click(uIIzračunajcijenuletaButton, new Point(133, 19));
        }
        
        /// <summary>
        /// RacunanjeTakseTest - Use 'RacunanjeTakseTestExpectedValues' to pass parameters into this method.
        /// </summary>
        public void RacunanjeTakseTest()
        {
            #region Variable Declarations
            WinEdit uITakseTxtEdit = this.UILufthansaRezervacijaWindow.UITakseTxtWindow.UITakseTxtEdit;
            #endregion

            // Verify that the 'Text' property of 'takseTxt' text box equals '58,1775346035972'
            Assert.AreEqual(this.RacunanjeTakseTestExpectedValues.UITakseTxtEditText, uITakseTxtEdit.Text, "Taksa nije pravilno izračunata!");
        }
        
        /// <summary>
        /// TaksaVanOpsega - Use 'TaksaVanOpsegaParams' to pass parameters into this method.
        /// </summary>
        public void TaksaVanOpsega()
        {
            #region Variable Declarations
            WinComboBox uIKomComboBox = this.UILufthansaRezervacijaWindow.UIPolazisteCBWindow.UIKomComboBox;
            WinButton uIOpenButton = this.UILufthansaRezervacijaWindow.UIOdredisteCBWindow.UIOpenButton;
            WinComboBox uIOdredisteCBComboBox = this.UILufthansaRezervacijaWindow.UIOdredisteCBWindow.UIOdredisteCBComboBox;
            WinEdit uIPrtljagTxtEdit = this.UILufthansaRezervacijaWindow.UIPrtljagTxtWindow.UIPrtljagTxtEdit;
            WinEdit uITakseTxtEdit = this.UILufthansaRezervacijaWindow.UITakseTxtWindow.UITakseTxtEdit;
            WinSlider uIKlasaBarSlider = this.UILufthansaRezervacijaWindow.UIKlasaBarWindow.UIKlasaBarSlider;
            WinClient uIPodacioletuClient = this.UILufthansaRezervacijaWindow.UIItemWindow.UIPodacioletuClient;
            WinEdit uICijenaTxtEdit = this.UILufthansaRezervacijaWindow.UICijenaTxtWindow.UICijenaTxtEdit;
            WinButton uIIzračunajcijenuletaButton = this.UILufthansaRezervacijaWindow.UIIzračunajcijenuletaWindow.UIIzračunajcijenuletaButton;
            #endregion

            // Last mouse action was not recorded.

            // Select 'Istanbul' in 'kom' combo box
            uIKomComboBox.SelectedItem = this.TaksaVanOpsegaParams.UIKomComboBoxSelectedItem;

            // Click 'Open' button
            Mouse.Click(uIOpenButton, new Point(9, 11));

            // Last mouse action was not recorded.

            // Select 'Pariz' in 'odredisteCB' combo box
            uIOdredisteCBComboBox.SelectedItem = this.TaksaVanOpsegaParams.UIOdredisteCBComboBoxSelectedItem;

            // Type '3' in 'prtljagTxt' text box
            uIPrtljagTxtEdit.Text = this.TaksaVanOpsegaParams.UIPrtljagTxtEditText;

            // Type '158' in 'takseTxt' text box
            uITakseTxtEdit.Text = this.TaksaVanOpsegaParams.UITakseTxtEditText;

            // Set position '5' in 'klasaBar' slider
            uIKlasaBarSlider.PositionAsString = this.TaksaVanOpsegaParams.UIKlasaBarSliderPositionAsString;

            // Click 'Podaci o letu' client
            Mouse.Click(uIPodacioletuClient, new Point(7, 9));

            // Click 'cijenaTxt' text box
            Mouse.Click(uICijenaTxtEdit, new Point(36, 13));

            // Click 'Izračunaj cijenu leta' button
            Mouse.Click(uIIzračunajcijenuletaButton, new Point(201, 22));
        }
        
        /// <summary>
        /// PrtljagNijeUnesenTest - Use 'PrtljagNijeUnesenTestExpectedValues' to pass parameters into this method.
        /// </summary>
        public void PrtljagNijeUnesenTest()
        {
            #region Variable Declarations
            WinText uIProvjeriteunesenepodText = this.UIProvjeriteunesenepodWindow.UIProvjeriteunesenepodText;
            #endregion

            // Verify that the 'DisplayText' property of 'Provjerite unesene podatke za let i putnika! Syste...' label contains 'Provjerite unesene podatke za let i putnika! '
            StringAssert.Contains(uIProvjeriteunesenepodText.DisplayText, this.PrtljagNijeUnesenTestExpectedValues.UIProvjeriteunesenepodTextDisplayText, "Validacija nije uredu!");
        }
        
        /// <summary>
        /// SviParametriUneseni - Use 'SviParametriUneseniParams' to pass parameters into this method.
        /// </summary>
        public void SviParametriUneseni()
        {
            #region Variable Declarations
            WinComboBox uIKomComboBox = this.UILufthansaRezervacijaWindow.UIPolazisteCBWindow.UIKomComboBox;
            WinComboBox uIOdredisteCBComboBox = this.UILufthansaRezervacijaWindow.UIOdredisteCBWindow.UIOdredisteCBComboBox;
            WinWindow uIPrtljagTxtWindow = this.UILufthansaRezervacijaWindow.UIPodacioletuGroup.UIPrtljagTxtWindow;
            WinEdit uIPrtljagTxtEdit = this.UILufthansaRezervacijaWindow.UIPrtljagTxtWindow.UIPrtljagTxtEdit;
            WinEdit uITakseTxtEdit = this.UILufthansaRezervacijaWindow.UITakseTxtWindow.UITakseTxtEdit;
            WinSlider uIKlasaBarSlider = this.UILufthansaRezervacijaWindow.UIKlasaBarWindow.UIKlasaBarSlider;
            WinButton uIIzračunajcijenuletaButton = this.UILufthansaRezervacijaWindow.UIIzračunajcijenuletaWindow.UIIzračunajcijenuletaButton;
            WinEdit uIImeTxtEdit = this.UILufthansaRezervacijaWindow.UIImeTxtWindow.UIImeTxtEdit;
            WinEdit uIPrezimeTxtEdit = this.UILufthansaRezervacijaWindow.UIPrezimeTxtWindow.UIPrezimeTxtEdit;
            WinEdit uIJmbgTxtEdit = this.UILufthansaRezervacijaWindow.UIJmbgTxtWindow.UIJmbgTxtEdit;
            WinEdit uITelefonTxtEdit = this.UILufthansaRezervacijaWindow.UITelefonTxtWindow.UITelefonTxtEdit;
            WinEdit uIKomentarTxtEdit = this.UILufthansaRezervacijaWindow.UIKomentarTxtWindow.UIKomentarTxtEdit;
            WinButton uIRezervišiletButton = this.UILufthansaRezervacijaWindow.UIRezervišiletWindow.UIRezervišiletButton;
            #endregion

            // Last mouse action was not recorded.

            // Select 'Sarajevo' in 'kom' combo box
            uIKomComboBox.SelectedItem = this.SviParametriUneseniParams.UIKomComboBoxSelectedItem;

            // Click 'odredisteCB' combo box
            Mouse.Click(uIOdredisteCBComboBox, new Point(60, 14));

            // Last mouse action was not recorded.

            // Select 'Pariz' in 'odredisteCB' combo box
            uIOdredisteCBComboBox.SelectedItem = this.SviParametriUneseniParams.UIOdredisteCBComboBoxSelectedItem;

            // Click 'prtljagTxt' window
            Mouse.Click(uIPrtljagTxtWindow, new Point(57, 0));

            // Type '3' in 'prtljagTxt' text box
            uIPrtljagTxtEdit.Text = this.SviParametriUneseniParams.UIPrtljagTxtEditText;

            // Type '50' in 'takseTxt' text box
            uITakseTxtEdit.Text = this.SviParametriUneseniParams.UITakseTxtEditText;

            // Set position '5' in 'klasaBar' slider
            uIKlasaBarSlider.PositionAsString = this.SviParametriUneseniParams.UIKlasaBarSliderPositionAsString;

            // Click 'Izračunaj cijenu leta' button
            Mouse.Click(uIIzračunajcijenuletaButton, new Point(196, 16));

            // Type 'Reufik' in 'imeTxt' text box
            uIImeTxtEdit.Text = this.SviParametriUneseniParams.UIImeTxtEditText;

            // Type '{Tab}' in 'imeTxt' text box
            Keyboard.SendKeys(uIImeTxtEdit, this.SviParametriUneseniParams.UIImeTxtEditSendKeys, ModifierKeys.None);

            // Type 'Mujkic' in 'prezimeTxt' text box
            uIPrezimeTxtEdit.Text = this.SviParametriUneseniParams.UIPrezimeTxtEditText;

            // Type '{Tab}' in 'prezimeTxt' text box
            Keyboard.SendKeys(uIPrezimeTxtEdit, this.SviParametriUneseniParams.UIPrezimeTxtEditSendKeys, ModifierKeys.None);

            // Type '1203975012102' in 'jmbgTxt' text box
            uIJmbgTxtEdit.Text = this.SviParametriUneseniParams.UIJmbgTxtEditText;

            // Type '{Tab}' in 'jmbgTxt' text box
            Keyboard.SendKeys(uIJmbgTxtEdit, this.SviParametriUneseniParams.UIJmbgTxtEditSendKeys, ModifierKeys.None);

            // Type '38761987812' in 'telefonTxt' text box
            uITelefonTxtEdit.Text = this.SviParametriUneseniParams.UITelefonTxtEditText;

            // Type '{Tab}' in 'telefonTxt' text box
            Keyboard.SendKeys(uITelefonTxtEdit, this.SviParametriUneseniParams.UITelefonTxtEditSendKeys, ModifierKeys.None);

            // Type 'Refko' in 'komentarTxt' text box
            uIKomentarTxtEdit.Text = this.SviParametriUneseniParams.UIKomentarTxtEditText;

            // Click 'Rezerviši let' button
            Mouse.Click(uIRezervišiletButton, new Point(183, 21));
        }
        
        /// <summary>
        /// Izbrisan red iz datagrid-a
        /// </summary>
        public void IzbirsanRed()
        {
            #region Variable Declarations
            WinRowHeader uIItemRowHeader = this.UILufthansaRezervacijaWindow.UIDataGridView1Window.UIDataGridViewTable.UIRow0Row.UIItemRowHeader;
            WinButton uIIzbrišiuneseniletButton = this.UILufthansaRezervacijaWindow.UIIzbrišiuneseniletWindow.UIIzbrišiuneseniletButton;
            #endregion

            // Last mouse action was not recorded.

            // Click row header
            Mouse.Click(uIItemRowHeader, new Point(6, 8));

            // Click 'Izbriši uneseni let' button
            Mouse.Click(uIIzbrišiuneseniletButton, new Point(193, 21));
        }
        
        /// <summary>
        /// Provjera distance Sarajevo-Pariz
        /// </summary>
        public void Distanca()
        {
            #region Variable Declarations
            WinComboBox uIKomComboBox = this.UILufthansaRezervacijaWindow.UIPolazisteCBWindow.UIKomComboBox;
            WinComboBox uIOdredisteCBComboBox = this.UILufthansaRezervacijaWindow.UIOdredisteCBWindow.UIOdredisteCBComboBox;
            #endregion

            // Last mouse action was not recorded.

            // Select 'Sarajevo' in 'kom' combo box
            uIKomComboBox.SelectedItem = this.DistancaParams.UIKomComboBoxSelectedItem;

            // Click 'odredisteCB' combo box
            Mouse.Click(uIOdredisteCBComboBox, new Point(30, 10));

            // Last mouse action was not recorded.

            // Select 'Pariz' in 'odredisteCB' combo box
            uIOdredisteCBComboBox.SelectedItem = this.DistancaParams.UIOdredisteCBComboBoxSelectedItem;
        }
        
        /// <summary>
        /// DistancaTest - Use 'DistancaTestExpectedValues' to pass parameters into this method.
        /// </summary>
        public void DistancaTest()
        {
            #region Variable Declarations
            WinEdit uIDistancaTxtEdit = this.UILufthansaRezervacijaWindow.UIDistancaTxtWindow.UIDistancaTxtEdit;
            #endregion

            // Verify that the 'Text' property of 'distancaTxt' text box equals '1350'
            Assert.AreEqual(this.DistancaTestExpectedValues.UIDistancaTxtEditText, uIDistancaTxtEdit.Text, "Pogrešno izračunata distanca!");
        }
        
        /// <summary>
        /// Serijalizacija - Use 'SerijalizacijaParams' to pass parameters into this method.
        /// </summary>
        public void Serijalizacija()
        {
            #region Variable Declarations
            WinComboBox uIKomComboBox = this.UILufthansaRezervacijaWindow.UIPolazisteCBWindow.UIKomComboBox;
            WinComboBox uIOdredisteCBComboBox = this.UILufthansaRezervacijaWindow.UIOdredisteCBWindow.UIOdredisteCBComboBox;
            WinEdit uIPrtljagTxtEdit = this.UILufthansaRezervacijaWindow.UIPrtljagTxtWindow.UIPrtljagTxtEdit;
            WinEdit uITakseTxtEdit = this.UILufthansaRezervacijaWindow.UITakseTxtWindow.UITakseTxtEdit;
            WinSlider uIKlasaBarSlider = this.UILufthansaRezervacijaWindow.UIKlasaBarWindow.UIKlasaBarSlider;
            WinButton uIIzračunajcijenuletaButton = this.UILufthansaRezervacijaWindow.UIIzračunajcijenuletaWindow.UIIzračunajcijenuletaButton;
            WinEdit uIImeTxtEdit = this.UILufthansaRezervacijaWindow.UIImeTxtWindow.UIImeTxtEdit;
            WinEdit uIPrezimeTxtEdit = this.UILufthansaRezervacijaWindow.UIPrezimeTxtWindow.UIPrezimeTxtEdit;
            WinEdit uIJmbgTxtEdit = this.UILufthansaRezervacijaWindow.UIJmbgTxtWindow.UIJmbgTxtEdit;
            WinEdit uITelefonTxtEdit = this.UILufthansaRezervacijaWindow.UITelefonTxtWindow.UITelefonTxtEdit;
            WinEdit uIKomentarTxtEdit = this.UILufthansaRezervacijaWindow.UIKomentarTxtWindow.UIKomentarTxtEdit;
            WinButton uIRezervišiletButton = this.UILufthansaRezervacijaWindow.UIRezervišiletWindow.UIRezervišiletButton;
            #endregion

            // Last mouse action was not recorded.

            // Select 'Istanbul' in 'kom' combo box
            uIKomComboBox.SelectedItem = this.SerijalizacijaParams.UIKomComboBoxSelectedItem;

            // Select 'Pariz' in 'odredisteCB' combo box
            uIOdredisteCBComboBox.SelectedItem = this.SerijalizacijaParams.UIOdredisteCBComboBoxSelectedItem;

            // Type '3' in 'prtljagTxt' text box
            uIPrtljagTxtEdit.Text = this.SerijalizacijaParams.UIPrtljagTxtEditText;

            // Type '95' in 'takseTxt' text box
            uITakseTxtEdit.Text = this.SerijalizacijaParams.UITakseTxtEditText;

            // Set position '10' in 'klasaBar' slider
            uIKlasaBarSlider.PositionAsString = this.SerijalizacijaParams.UIKlasaBarSliderPositionAsString;

            // Click 'Izračunaj cijenu leta' button
            Mouse.Click(uIIzračunajcijenuletaButton, new Point(143, 22));

            // Type 'Djido' in 'imeTxt' text box
            uIImeTxtEdit.Text = this.SerijalizacijaParams.UIImeTxtEditText;

            // Type '{Tab}' in 'imeTxt' text box
            Keyboard.SendKeys(uIImeTxtEdit, this.SerijalizacijaParams.UIImeTxtEditSendKeys, ModifierKeys.None);

            // Type 'Mova' in 'prezimeTxt' text box
            uIPrezimeTxtEdit.Text = this.SerijalizacijaParams.UIPrezimeTxtEditText;

            // Type '{Tab}' in 'prezimeTxt' text box
            Keyboard.SendKeys(uIPrezimeTxtEdit, this.SerijalizacijaParams.UIPrezimeTxtEditSendKeys, ModifierKeys.None);

            // Type '0707977007007' in 'jmbgTxt' text box
            uIJmbgTxtEdit.Text = this.SerijalizacijaParams.UIJmbgTxtEditText;

            // Type '{Tab}' in 'jmbgTxt' text box
            Keyboard.SendKeys(uIJmbgTxtEdit, this.SerijalizacijaParams.UIJmbgTxtEditSendKeys, ModifierKeys.None);

            // Type '38761007007' in 'telefonTxt' text box
            uITelefonTxtEdit.Text = this.SerijalizacijaParams.UITelefonTxtEditText;

            // Type '{Tab}' in 'telefonTxt' text box
            Keyboard.SendKeys(uITelefonTxtEdit, this.SerijalizacijaParams.UITelefonTxtEditSendKeys, ModifierKeys.None);

            // Type 'bez komentara' in 'komentarTxt' text box
            uIKomentarTxtEdit.Text = this.SerijalizacijaParams.UIKomentarTxtEditText;

            // Click 'Rezerviši let' button
            Mouse.Click(uIRezervišiletButton, new Point(149, 28));
        }
        
        /// <summary>
        /// SerijalizacijaTest - Use 'SerijalizacijaTestExpectedValues' to pass parameters into this method.
        /// </summary>
        public void SerijalizacijaTest()
        {
            #region Variable Declarations
            WinCell uIDjidoMovaCell = this.UILufthansaRezervacijaWindow.UIDataGridView1Window.UIDataGridViewTable.UIRow2Row.UIDjidoMovaCell;
            WinCell uIItem38761007007Cell = this.UILufthansaRezervacijaWindow.UIDataGridView1Window.UIDataGridViewTable.UIRow2Row.UIItem38761007007Cell;
            #endregion

            // Verify that the 'Value' property of 'Djido Mova' cell equals 'Djido Mova'
            Assert.AreEqual(this.SerijalizacijaTestExpectedValues.UIDjidoMovaCellValue, uIDjidoMovaCell.Value, "Ime i prezime pogresno!");

            // Verify that the 'Value' property of '38761007007' cell equals '38761007007'
            Assert.AreEqual(this.SerijalizacijaTestExpectedValues.UIItem38761007007CellValue, uIItem38761007007Cell.Value, "JMBG pogresan!");
        }
        
        #region Properties
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public virtual SviParametriUneseniTestExpectedValues SviParametriUneseniTestExpectedValues
        {
            get
            {
                if ((this.mSviParametriUneseniTestExpectedValues == null))
                {
                    this.mSviParametriUneseniTestExpectedValues = new SviParametriUneseniTestExpectedValues();
                }
                return this.mSviParametriUneseniTestExpectedValues;
            }
        }
        
        public virtual PrtljagNijeUnesenParams PrtljagNijeUnesenParams
        {
            get
            {
                if ((this.mPrtljagNijeUnesenParams == null))
                {
                    this.mPrtljagNijeUnesenParams = new PrtljagNijeUnesenParams();
                }
                return this.mPrtljagNijeUnesenParams;
            }
        }
        
        public virtual RacunanjeTakseParams RacunanjeTakseParams
        {
            get
            {
                if ((this.mRacunanjeTakseParams == null))
                {
                    this.mRacunanjeTakseParams = new RacunanjeTakseParams();
                }
                return this.mRacunanjeTakseParams;
            }
        }
        
        public virtual RacunanjeTakseTestExpectedValues RacunanjeTakseTestExpectedValues
        {
            get
            {
                if ((this.mRacunanjeTakseTestExpectedValues == null))
                {
                    this.mRacunanjeTakseTestExpectedValues = new RacunanjeTakseTestExpectedValues();
                }
                return this.mRacunanjeTakseTestExpectedValues;
            }
        }
        
        public virtual TaksaVanOpsegaParams TaksaVanOpsegaParams
        {
            get
            {
                if ((this.mTaksaVanOpsegaParams == null))
                {
                    this.mTaksaVanOpsegaParams = new TaksaVanOpsegaParams();
                }
                return this.mTaksaVanOpsegaParams;
            }
        }
        
        public virtual PrtljagNijeUnesenTestExpectedValues PrtljagNijeUnesenTestExpectedValues
        {
            get
            {
                if ((this.mPrtljagNijeUnesenTestExpectedValues == null))
                {
                    this.mPrtljagNijeUnesenTestExpectedValues = new PrtljagNijeUnesenTestExpectedValues();
                }
                return this.mPrtljagNijeUnesenTestExpectedValues;
            }
        }
        
        public virtual SviParametriUneseniParams SviParametriUneseniParams
        {
            get
            {
                if ((this.mSviParametriUneseniParams == null))
                {
                    this.mSviParametriUneseniParams = new SviParametriUneseniParams();
                }
                return this.mSviParametriUneseniParams;
            }
        }
        
        public virtual DistancaParams DistancaParams
        {
            get
            {
                if ((this.mDistancaParams == null))
                {
                    this.mDistancaParams = new DistancaParams();
                }
                return this.mDistancaParams;
            }
        }
        
        public virtual DistancaTestExpectedValues DistancaTestExpectedValues
        {
            get
            {
                if ((this.mDistancaTestExpectedValues == null))
                {
                    this.mDistancaTestExpectedValues = new DistancaTestExpectedValues();
                }
                return this.mDistancaTestExpectedValues;
            }
        }
        
        public virtual SerijalizacijaParams SerijalizacijaParams
        {
            get
            {
                if ((this.mSerijalizacijaParams == null))
                {
                    this.mSerijalizacijaParams = new SerijalizacijaParams();
                }
                return this.mSerijalizacijaParams;
            }
        }
        
        public virtual SerijalizacijaTestExpectedValues SerijalizacijaTestExpectedValues
        {
            get
            {
                if ((this.mSerijalizacijaTestExpectedValues == null))
                {
                    this.mSerijalizacijaTestExpectedValues = new SerijalizacijaTestExpectedValues();
                }
                return this.mSerijalizacijaTestExpectedValues;
            }
        }
        
        public UILufthansaRezervacijaWindow UILufthansaRezervacijaWindow
        {
            get
            {
                if ((this.mUILufthansaRezervacijaWindow == null))
                {
                    this.mUILufthansaRezervacijaWindow = new UILufthansaRezervacijaWindow();
                }
                return this.mUILufthansaRezervacijaWindow;
            }
        }
        
        public UIProvjeriteunesenepodWindow UIProvjeriteunesenepodWindow
        {
            get
            {
                if ((this.mUIProvjeriteunesenepodWindow == null))
                {
                    this.mUIProvjeriteunesenepodWindow = new UIProvjeriteunesenepodWindow();
                }
                return this.mUIProvjeriteunesenepodWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private SviParametriUneseniTestExpectedValues mSviParametriUneseniTestExpectedValues;
        
        private PrtljagNijeUnesenParams mPrtljagNijeUnesenParams;
        
        private RacunanjeTakseParams mRacunanjeTakseParams;
        
        private RacunanjeTakseTestExpectedValues mRacunanjeTakseTestExpectedValues;
        
        private TaksaVanOpsegaParams mTaksaVanOpsegaParams;
        
        private PrtljagNijeUnesenTestExpectedValues mPrtljagNijeUnesenTestExpectedValues;
        
        private SviParametriUneseniParams mSviParametriUneseniParams;
        
        private DistancaParams mDistancaParams;
        
        private DistancaTestExpectedValues mDistancaTestExpectedValues;
        
        private SerijalizacijaParams mSerijalizacijaParams;
        
        private SerijalizacijaTestExpectedValues mSerijalizacijaTestExpectedValues;
        
        private UILufthansaRezervacijaWindow mUILufthansaRezervacijaWindow;
        
        private UIProvjeriteunesenepodWindow mUIProvjeriteunesenepodWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Select 'Sarajevo' in 'kom' combo box
        /// </summary>
        public string UIKomComboBoxSelectedItem = "Sarajevo";
        
        /// <summary>
        /// Select 'Istanbul' in 'odredisteCB' combo box
        /// </summary>
        public string UIOdredisteCBComboBoxSelectedItem = "Istanbul";
        
        /// <summary>
        /// Type '2' in 'prtljagTxt' text box
        /// </summary>
        public string UIPrtljagTxtEditText = "2";
        
        /// <summary>
        /// Type '{Tab}' in 'prtljagTxt' text box
        /// </summary>
        public string UIPrtljagTxtEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '50' in 'takseTxt' text box
        /// </summary>
        public string UITakseTxtEditText = "50";
        
        /// <summary>
        /// Set position '5' in 'klasaBar' slider
        /// </summary>
        public string UIKlasaBarSliderPositionAsString = "5";
        
        /// <summary>
        /// Type 'Imenko' in 'imeTxt' text box
        /// </summary>
        public string UIImeTxtEditText = "Imenko";
        
        /// <summary>
        /// Type '{Tab}' in 'imeTxt' text box
        /// </summary>
        public string UIImeTxtEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'Prezimenko' in 'prezimeTxt' text box
        /// </summary>
        public string UIPrezimeTxtEditText = "Prezimenko";
        
        /// <summary>
        /// Type '{Tab}' in 'prezimeTxt' text box
        /// </summary>
        public string UIPrezimeTxtEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '0123456789123' in 'jmbgTxt' text box
        /// </summary>
        public string UIJmbgTxtEditText = "0123456789123";
        
        /// <summary>
        /// Type '{Tab}' in 'jmbgTxt' text box
        /// </summary>
        public string UIJmbgTxtEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '38761123456' in 'telefonTxt' text box
        /// </summary>
        public string UITelefonTxtEditText = "38761123456";
        
        /// <summary>
        /// Type '{Tab}' in 'telefonTxt' text box
        /// </summary>
        public string UITelefonTxtEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'komentar' in 'komentarTxt' text box
        /// </summary>
        public string UIKomentarTxtEditText = "komentar";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'SviParametriUneseniTest'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class SviParametriUneseniTestExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Text' property of 'distancaTxt' text box is not equal to '0'
        /// </summary>
        public string UIDistancaTxtEditText = "0";
        
        /// <summary>
        /// Verify that the 'Text' property of 'prtljagTxt' text box is not equal to ''
        /// </summary>
        public string UIPrtljagTxtEditText = "";
        
        /// <summary>
        /// Verify that the 'Text' property of 'takseTxt' text box is not equal to ''
        /// </summary>
        public string UITakseTxtEditText = "";
        
        /// <summary>
        /// Verify that the 'Text' property of 'cijenaTxt' text box is not equal to ''
        /// </summary>
        public string UICijenaTxtEditText = "";
        
        /// <summary>
        /// Verify that the 'Text' property of 'imeTxt' text box is not equal to ''
        /// </summary>
        public string UIImeTxtEditText = "";
        
        /// <summary>
        /// Verify that the 'Text' property of 'prezimeTxt' text box is not equal to ''
        /// </summary>
        public string UIPrezimeTxtEditText = "";
        
        /// <summary>
        /// Verify that the 'Text' property of 'jmbgTxt' text box is not equal to ''
        /// </summary>
        public string UIJmbgTxtEditText = "";
        
        /// <summary>
        /// Verify that the 'Text' property of 'telefonTxt' text box is not equal to ''
        /// </summary>
        public string UITelefonTxtEditText = "";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'PrtljagNijeUnesen'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class PrtljagNijeUnesenParams
    {
        
        #region Fields
        /// <summary>
        /// Select 'Istanbul' in 'kom' combo box
        /// </summary>
        public string UIKomComboBoxSelectedItem = "Istanbul";
        
        /// <summary>
        /// Select 'Sarajevo' in 'odredisteCB' combo box
        /// </summary>
        public string UIOdredisteCBComboBoxSelectedItem = "Sarajevo";
        
        /// <summary>
        /// Type '5' in 'prtljagTxt' text box
        /// </summary>
        public string UIPrtljagTxtEditText = "5";
        
        /// <summary>
        /// Type '70' in 'takseTxt' text box
        /// </summary>
        public string UITakseTxtEditText = "70";
        
        /// <summary>
        /// Set position '9' in 'klasaBar' slider
        /// </summary>
        public string UIKlasaBarSliderPositionAsString = "9";
        
        /// <summary>
        /// Type 'Reufik' in 'imeTxt' text box
        /// </summary>
        public string UIImeTxtEditText = "Reufik";
        
        /// <summary>
        /// Type '{Tab}' in 'imeTxt' text box
        /// </summary>
        public string UIImeTxtEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'Mujkic' in 'prezimeTxt' text box
        /// </summary>
        public string UIPrezimeTxtEditText = "Mujkic";
        
        /// <summary>
        /// Type '{Tab}' in 'prezimeTxt' text box
        /// </summary>
        public string UIPrezimeTxtEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '1203975012310' in 'jmbgTxt' text box
        /// </summary>
        public string UIJmbgTxtEditText = "1203975012310";
        
        /// <summary>
        /// Type '{Tab}' in 'jmbgTxt' text box
        /// </summary>
        public string UIJmbgTxtEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '38761111222' in 'telefonTxt' text box
        /// </summary>
        public string UITelefonTxtEditText = "38761111222";
        
        /// <summary>
        /// Type 'Refko' in 'komentarTxt' text box
        /// </summary>
        public string UIKomentarTxtEditText = "Refko";
        
        /// <summary>
        /// Type '' in 'prtljagTxt' text box
        /// </summary>
        public string UIPrtljagTxtEditText1 = "";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RacunanjeTakse'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class RacunanjeTakseParams
    {
        
        #region Fields
        /// <summary>
        /// Select 'Sarajevo' in 'kom' combo box
        /// </summary>
        public string UIKomComboBoxSelectedItem = "Sarajevo";
        
        /// <summary>
        /// Select 'Pariz' in 'odredisteCB' combo box
        /// </summary>
        public string UIOdredisteCBComboBoxSelectedItem = "Pariz";
        
        /// <summary>
        /// Type '2' in 'prtljagTxt' text box
        /// </summary>
        public string UIPrtljagTxtEditText = "2";
        
        /// <summary>
        /// Type '250' in 'cijenaTxt' text box
        /// </summary>
        public string UICijenaTxtEditText = "250";
        
        /// <summary>
        /// Set position '5' in 'klasaBar' slider
        /// </summary>
        public string UIKlasaBarSliderPositionAsString = "5";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RacunanjeTakseTest'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class RacunanjeTakseTestExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Text' property of 'takseTxt' text box equals '58,1775346035972'
        /// </summary>
        public string UITakseTxtEditText = "58,1775346035972";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TaksaVanOpsega'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class TaksaVanOpsegaParams
    {
        
        #region Fields
        /// <summary>
        /// Select 'Istanbul' in 'kom' combo box
        /// </summary>
        public string UIKomComboBoxSelectedItem = "Istanbul";
        
        /// <summary>
        /// Select 'Pariz' in 'odredisteCB' combo box
        /// </summary>
        public string UIOdredisteCBComboBoxSelectedItem = "Pariz";
        
        /// <summary>
        /// Type '3' in 'prtljagTxt' text box
        /// </summary>
        public string UIPrtljagTxtEditText = "3";
        
        /// <summary>
        /// Type '158' in 'takseTxt' text box
        /// </summary>
        public string UITakseTxtEditText = "158";
        
        /// <summary>
        /// Set position '5' in 'klasaBar' slider
        /// </summary>
        public string UIKlasaBarSliderPositionAsString = "5";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'PrtljagNijeUnesenTest'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class PrtljagNijeUnesenTestExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'DisplayText' property of 'Provjerite unesene podatke za let i putnika! Syste...' label contains 'Provjerite unesene podatke za let i putnika! '
        /// </summary>
        public string UIProvjeriteunesenepodTextDisplayText = "Provjerite unesene podatke za let i putnika! ";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'SviParametriUneseni'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class SviParametriUneseniParams
    {
        
        #region Fields
        /// <summary>
        /// Select 'Sarajevo' in 'kom' combo box
        /// </summary>
        public string UIKomComboBoxSelectedItem = "Sarajevo";
        
        /// <summary>
        /// Select 'Pariz' in 'odredisteCB' combo box
        /// </summary>
        public string UIOdredisteCBComboBoxSelectedItem = "Pariz";
        
        /// <summary>
        /// Type '3' in 'prtljagTxt' text box
        /// </summary>
        public string UIPrtljagTxtEditText = "3";
        
        /// <summary>
        /// Type '50' in 'takseTxt' text box
        /// </summary>
        public string UITakseTxtEditText = "50";
        
        /// <summary>
        /// Set position '5' in 'klasaBar' slider
        /// </summary>
        public string UIKlasaBarSliderPositionAsString = "5";
        
        /// <summary>
        /// Type 'Reufik' in 'imeTxt' text box
        /// </summary>
        public string UIImeTxtEditText = "Reufik";
        
        /// <summary>
        /// Type '{Tab}' in 'imeTxt' text box
        /// </summary>
        public string UIImeTxtEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'Mujkic' in 'prezimeTxt' text box
        /// </summary>
        public string UIPrezimeTxtEditText = "Mujkic";
        
        /// <summary>
        /// Type '{Tab}' in 'prezimeTxt' text box
        /// </summary>
        public string UIPrezimeTxtEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '1203975012102' in 'jmbgTxt' text box
        /// </summary>
        public string UIJmbgTxtEditText = "1203975012102";
        
        /// <summary>
        /// Type '{Tab}' in 'jmbgTxt' text box
        /// </summary>
        public string UIJmbgTxtEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '38761987812' in 'telefonTxt' text box
        /// </summary>
        public string UITelefonTxtEditText = "38761987812";
        
        /// <summary>
        /// Type '{Tab}' in 'telefonTxt' text box
        /// </summary>
        public string UITelefonTxtEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'Refko' in 'komentarTxt' text box
        /// </summary>
        public string UIKomentarTxtEditText = "Refko";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Distanca'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class DistancaParams
    {
        
        #region Fields
        /// <summary>
        /// Select 'Sarajevo' in 'kom' combo box
        /// </summary>
        public string UIKomComboBoxSelectedItem = "Sarajevo";
        
        /// <summary>
        /// Select 'Pariz' in 'odredisteCB' combo box
        /// </summary>
        public string UIOdredisteCBComboBoxSelectedItem = "Pariz";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'DistancaTest'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class DistancaTestExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Text' property of 'distancaTxt' text box equals '1350'
        /// </summary>
        public string UIDistancaTxtEditText = "1350";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Serijalizacija'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class SerijalizacijaParams
    {
        
        #region Fields
        /// <summary>
        /// Select 'Istanbul' in 'kom' combo box
        /// </summary>
        public string UIKomComboBoxSelectedItem = "Istanbul";
        
        /// <summary>
        /// Select 'Pariz' in 'odredisteCB' combo box
        /// </summary>
        public string UIOdredisteCBComboBoxSelectedItem = "Pariz";
        
        /// <summary>
        /// Type '3' in 'prtljagTxt' text box
        /// </summary>
        public string UIPrtljagTxtEditText = "3";
        
        /// <summary>
        /// Type '95' in 'takseTxt' text box
        /// </summary>
        public string UITakseTxtEditText = "95";
        
        /// <summary>
        /// Set position '10' in 'klasaBar' slider
        /// </summary>
        public string UIKlasaBarSliderPositionAsString = "10";
        
        /// <summary>
        /// Type 'Djido' in 'imeTxt' text box
        /// </summary>
        public string UIImeTxtEditText = "Djido";
        
        /// <summary>
        /// Type '{Tab}' in 'imeTxt' text box
        /// </summary>
        public string UIImeTxtEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'Mova' in 'prezimeTxt' text box
        /// </summary>
        public string UIPrezimeTxtEditText = "Mova";
        
        /// <summary>
        /// Type '{Tab}' in 'prezimeTxt' text box
        /// </summary>
        public string UIPrezimeTxtEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '0707977007007' in 'jmbgTxt' text box
        /// </summary>
        public string UIJmbgTxtEditText = "0707977007007";
        
        /// <summary>
        /// Type '{Tab}' in 'jmbgTxt' text box
        /// </summary>
        public string UIJmbgTxtEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '38761007007' in 'telefonTxt' text box
        /// </summary>
        public string UITelefonTxtEditText = "38761007007";
        
        /// <summary>
        /// Type '{Tab}' in 'telefonTxt' text box
        /// </summary>
        public string UITelefonTxtEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'bez komentara' in 'komentarTxt' text box
        /// </summary>
        public string UIKomentarTxtEditText = "bez komentara";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'SerijalizacijaTest'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class SerijalizacijaTestExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Value' property of 'Djido Mova' cell equals 'Djido Mova'
        /// </summary>
        public string UIDjidoMovaCellValue = "Djido Mova";
        
        /// <summary>
        /// Verify that the 'Value' property of '38761007007' cell equals '38761007007'
        /// </summary>
        public string UIItem38761007007CellValue = "38761007007";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UILufthansaRezervacijaWindow : WinWindow
    {
        
        public UILufthansaRezervacijaWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Lufthansa - Rezervacija leta";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Lufthansa - Rezervacija leta");
            #endregion
        }
        
        #region Properties
        public UIPolazisteCBWindow UIPolazisteCBWindow
        {
            get
            {
                if ((this.mUIPolazisteCBWindow == null))
                {
                    this.mUIPolazisteCBWindow = new UIPolazisteCBWindow(this);
                }
                return this.mUIPolazisteCBWindow;
            }
        }
        
        public UIOdredisteCBWindow UIOdredisteCBWindow
        {
            get
            {
                if ((this.mUIOdredisteCBWindow == null))
                {
                    this.mUIOdredisteCBWindow = new UIOdredisteCBWindow(this);
                }
                return this.mUIOdredisteCBWindow;
            }
        }
        
        public UIPrtljagTxtWindow UIPrtljagTxtWindow
        {
            get
            {
                if ((this.mUIPrtljagTxtWindow == null))
                {
                    this.mUIPrtljagTxtWindow = new UIPrtljagTxtWindow(this);
                }
                return this.mUIPrtljagTxtWindow;
            }
        }
        
        public UITakseTxtWindow UITakseTxtWindow
        {
            get
            {
                if ((this.mUITakseTxtWindow == null))
                {
                    this.mUITakseTxtWindow = new UITakseTxtWindow(this);
                }
                return this.mUITakseTxtWindow;
            }
        }
        
        public UIKlasaBarWindow UIKlasaBarWindow
        {
            get
            {
                if ((this.mUIKlasaBarWindow == null))
                {
                    this.mUIKlasaBarWindow = new UIKlasaBarWindow(this);
                }
                return this.mUIKlasaBarWindow;
            }
        }
        
        public UIIzračunajcijenuletaWindow UIIzračunajcijenuletaWindow
        {
            get
            {
                if ((this.mUIIzračunajcijenuletaWindow == null))
                {
                    this.mUIIzračunajcijenuletaWindow = new UIIzračunajcijenuletaWindow(this);
                }
                return this.mUIIzračunajcijenuletaWindow;
            }
        }
        
        public UIImeTxtWindow UIImeTxtWindow
        {
            get
            {
                if ((this.mUIImeTxtWindow == null))
                {
                    this.mUIImeTxtWindow = new UIImeTxtWindow(this);
                }
                return this.mUIImeTxtWindow;
            }
        }
        
        public UIPrezimeTxtWindow UIPrezimeTxtWindow
        {
            get
            {
                if ((this.mUIPrezimeTxtWindow == null))
                {
                    this.mUIPrezimeTxtWindow = new UIPrezimeTxtWindow(this);
                }
                return this.mUIPrezimeTxtWindow;
            }
        }
        
        public UIJmbgTxtWindow UIJmbgTxtWindow
        {
            get
            {
                if ((this.mUIJmbgTxtWindow == null))
                {
                    this.mUIJmbgTxtWindow = new UIJmbgTxtWindow(this);
                }
                return this.mUIJmbgTxtWindow;
            }
        }
        
        public UITelefonTxtWindow UITelefonTxtWindow
        {
            get
            {
                if ((this.mUITelefonTxtWindow == null))
                {
                    this.mUITelefonTxtWindow = new UITelefonTxtWindow(this);
                }
                return this.mUITelefonTxtWindow;
            }
        }
        
        public UIKomentarTxtWindow UIKomentarTxtWindow
        {
            get
            {
                if ((this.mUIKomentarTxtWindow == null))
                {
                    this.mUIKomentarTxtWindow = new UIKomentarTxtWindow(this);
                }
                return this.mUIKomentarTxtWindow;
            }
        }
        
        public UIRezervišiletWindow UIRezervišiletWindow
        {
            get
            {
                if ((this.mUIRezervišiletWindow == null))
                {
                    this.mUIRezervišiletWindow = new UIRezervišiletWindow(this);
                }
                return this.mUIRezervišiletWindow;
            }
        }
        
        public UIDistancaTxtWindow UIDistancaTxtWindow
        {
            get
            {
                if ((this.mUIDistancaTxtWindow == null))
                {
                    this.mUIDistancaTxtWindow = new UIDistancaTxtWindow(this);
                }
                return this.mUIDistancaTxtWindow;
            }
        }
        
        public UICijenaTxtWindow UICijenaTxtWindow
        {
            get
            {
                if ((this.mUICijenaTxtWindow == null))
                {
                    this.mUICijenaTxtWindow = new UICijenaTxtWindow(this);
                }
                return this.mUICijenaTxtWindow;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIPodacioletuGroup UIPodacioletuGroup
        {
            get
            {
                if ((this.mUIPodacioletuGroup == null))
                {
                    this.mUIPodacioletuGroup = new UIPodacioletuGroup(this);
                }
                return this.mUIPodacioletuGroup;
            }
        }
        
        public UIDataGridView1Window UIDataGridView1Window
        {
            get
            {
                if ((this.mUIDataGridView1Window == null))
                {
                    this.mUIDataGridView1Window = new UIDataGridView1Window(this);
                }
                return this.mUIDataGridView1Window;
            }
        }
        
        public UIIzbrišiuneseniletWindow UIIzbrišiuneseniletWindow
        {
            get
            {
                if ((this.mUIIzbrišiuneseniletWindow == null))
                {
                    this.mUIIzbrišiuneseniletWindow = new UIIzbrišiuneseniletWindow(this);
                }
                return this.mUIIzbrišiuneseniletWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIPolazisteCBWindow mUIPolazisteCBWindow;
        
        private UIOdredisteCBWindow mUIOdredisteCBWindow;
        
        private UIPrtljagTxtWindow mUIPrtljagTxtWindow;
        
        private UITakseTxtWindow mUITakseTxtWindow;
        
        private UIKlasaBarWindow mUIKlasaBarWindow;
        
        private UIIzračunajcijenuletaWindow mUIIzračunajcijenuletaWindow;
        
        private UIImeTxtWindow mUIImeTxtWindow;
        
        private UIPrezimeTxtWindow mUIPrezimeTxtWindow;
        
        private UIJmbgTxtWindow mUIJmbgTxtWindow;
        
        private UITelefonTxtWindow mUITelefonTxtWindow;
        
        private UIKomentarTxtWindow mUIKomentarTxtWindow;
        
        private UIRezervišiletWindow mUIRezervišiletWindow;
        
        private UIDistancaTxtWindow mUIDistancaTxtWindow;
        
        private UICijenaTxtWindow mUICijenaTxtWindow;
        
        private UIItemWindow mUIItemWindow;
        
        private UIPodacioletuGroup mUIPodacioletuGroup;
        
        private UIDataGridView1Window mUIDataGridView1Window;
        
        private UIIzbrišiuneseniletWindow mUIIzbrišiuneseniletWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIPolazisteCBWindow : WinWindow
    {
        
        public UIPolazisteCBWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "polazisteCB";
            this.WindowTitles.Add("Lufthansa - Rezervacija leta");
            #endregion
        }
        
        #region Properties
        public WinComboBox UIKomComboBox
        {
            get
            {
                if ((this.mUIKomComboBox == null))
                {
                    this.mUIKomComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUIKomComboBox.SearchProperties[WinComboBox.PropertyNames.Name] = "kom";
                    this.mUIKomComboBox.WindowTitles.Add("Lufthansa - Rezervacija leta");
                    #endregion
                }
                return this.mUIKomComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUIKomComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIOdredisteCBWindow : WinWindow
    {
        
        public UIOdredisteCBWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "odredisteCB";
            this.WindowTitles.Add("Lufthansa - Rezervacija leta");
            #endregion
        }
        
        #region Properties
        public WinButton UIOpenButton
        {
            get
            {
                if ((this.mUIOpenButton == null))
                {
                    this.mUIOpenButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIOpenButton.SearchProperties[WinButton.PropertyNames.Name] = "Open";
                    this.mUIOpenButton.WindowTitles.Add("Lufthansa - Rezervacija leta");
                    #endregion
                }
                return this.mUIOpenButton;
            }
        }
        
        public WinComboBox UIOdredisteCBComboBox
        {
            get
            {
                if ((this.mUIOdredisteCBComboBox == null))
                {
                    this.mUIOdredisteCBComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUIOdredisteCBComboBox.WindowTitles.Add("Lufthansa - Rezervacija leta");
                    #endregion
                }
                return this.mUIOdredisteCBComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOpenButton;
        
        private WinComboBox mUIOdredisteCBComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIPrtljagTxtWindow : WinWindow
    {
        
        public UIPrtljagTxtWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "prtljagTxt";
            this.WindowTitles.Add("Lufthansa - Rezervacija leta");
            #endregion
        }
        
        #region Properties
        public WinEdit UIPrtljagTxtEdit
        {
            get
            {
                if ((this.mUIPrtljagTxtEdit == null))
                {
                    this.mUIPrtljagTxtEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIPrtljagTxtEdit.WindowTitles.Add("Lufthansa - Rezervacija leta");
                    #endregion
                }
                return this.mUIPrtljagTxtEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIPrtljagTxtEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UITakseTxtWindow : WinWindow
    {
        
        public UITakseTxtWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "takseTxt";
            this.WindowTitles.Add("Lufthansa - Rezervacija leta");
            #endregion
        }
        
        #region Properties
        public WinEdit UITakseTxtEdit
        {
            get
            {
                if ((this.mUITakseTxtEdit == null))
                {
                    this.mUITakseTxtEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITakseTxtEdit.WindowTitles.Add("Lufthansa - Rezervacija leta");
                    #endregion
                }
                return this.mUITakseTxtEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITakseTxtEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIKlasaBarWindow : WinWindow
    {
        
        public UIKlasaBarWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "klasaBar";
            this.WindowTitles.Add("Lufthansa - Rezervacija leta");
            #endregion
        }
        
        #region Properties
        public WinSlider UIKlasaBarSlider
        {
            get
            {
                if ((this.mUIKlasaBarSlider == null))
                {
                    this.mUIKlasaBarSlider = new WinSlider(this);
                    #region Search Criteria
                    this.mUIKlasaBarSlider.WindowTitles.Add("Lufthansa - Rezervacija leta");
                    #endregion
                }
                return this.mUIKlasaBarSlider;
            }
        }
        #endregion
        
        #region Fields
        private WinSlider mUIKlasaBarSlider;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIIzračunajcijenuletaWindow : WinWindow
    {
        
        public UIIzračunajcijenuletaWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "cijenaBtn";
            this.WindowTitles.Add("Lufthansa - Rezervacija leta");
            #endregion
        }
        
        #region Properties
        public WinButton UIIzračunajcijenuletaButton
        {
            get
            {
                if ((this.mUIIzračunajcijenuletaButton == null))
                {
                    this.mUIIzračunajcijenuletaButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIIzračunajcijenuletaButton.SearchProperties[WinButton.PropertyNames.Name] = "Izračunaj cijenu leta";
                    this.mUIIzračunajcijenuletaButton.WindowTitles.Add("Lufthansa - Rezervacija leta");
                    #endregion
                }
                return this.mUIIzračunajcijenuletaButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIIzračunajcijenuletaButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIImeTxtWindow : WinWindow
    {
        
        public UIImeTxtWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "imeTxt";
            this.WindowTitles.Add("Lufthansa - Rezervacija leta");
            #endregion
        }
        
        #region Properties
        public WinEdit UIImeTxtEdit
        {
            get
            {
                if ((this.mUIImeTxtEdit == null))
                {
                    this.mUIImeTxtEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIImeTxtEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Komentar:";
                    this.mUIImeTxtEdit.WindowTitles.Add("Lufthansa - Rezervacija leta");
                    #endregion
                }
                return this.mUIImeTxtEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIImeTxtEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIPrezimeTxtWindow : WinWindow
    {
        
        public UIPrezimeTxtWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "prezimeTxt";
            this.WindowTitles.Add("Lufthansa - Rezervacija leta");
            #endregion
        }
        
        #region Properties
        public WinEdit UIPrezimeTxtEdit
        {
            get
            {
                if ((this.mUIPrezimeTxtEdit == null))
                {
                    this.mUIPrezimeTxtEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIPrezimeTxtEdit.WindowTitles.Add("Lufthansa - Rezervacija leta");
                    #endregion
                }
                return this.mUIPrezimeTxtEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIPrezimeTxtEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIJmbgTxtWindow : WinWindow
    {
        
        public UIJmbgTxtWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "jmbgTxt";
            this.WindowTitles.Add("Lufthansa - Rezervacija leta");
            #endregion
        }
        
        #region Properties
        public WinEdit UIJmbgTxtEdit
        {
            get
            {
                if ((this.mUIJmbgTxtEdit == null))
                {
                    this.mUIJmbgTxtEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIJmbgTxtEdit.WindowTitles.Add("Lufthansa - Rezervacija leta");
                    #endregion
                }
                return this.mUIJmbgTxtEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIJmbgTxtEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UITelefonTxtWindow : WinWindow
    {
        
        public UITelefonTxtWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "telefonTxt";
            this.WindowTitles.Add("Lufthansa - Rezervacija leta");
            #endregion
        }
        
        #region Properties
        public WinEdit UITelefonTxtEdit
        {
            get
            {
                if ((this.mUITelefonTxtEdit == null))
                {
                    this.mUITelefonTxtEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITelefonTxtEdit.WindowTitles.Add("Lufthansa - Rezervacija leta");
                    #endregion
                }
                return this.mUITelefonTxtEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITelefonTxtEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIKomentarTxtWindow : WinWindow
    {
        
        public UIKomentarTxtWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "komentarTxt";
            this.WindowTitles.Add("Lufthansa - Rezervacija leta");
            #endregion
        }
        
        #region Properties
        public WinEdit UIKomentarTxtEdit
        {
            get
            {
                if ((this.mUIKomentarTxtEdit == null))
                {
                    this.mUIKomentarTxtEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIKomentarTxtEdit.WindowTitles.Add("Lufthansa - Rezervacija leta");
                    #endregion
                }
                return this.mUIKomentarTxtEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIKomentarTxtEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIRezervišiletWindow : WinWindow
    {
        
        public UIRezervišiletWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "rezervacijaBtn";
            this.WindowTitles.Add("Lufthansa - Rezervacija leta");
            #endregion
        }
        
        #region Properties
        public WinButton UIRezervišiletButton
        {
            get
            {
                if ((this.mUIRezervišiletButton == null))
                {
                    this.mUIRezervišiletButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIRezervišiletButton.SearchProperties[WinButton.PropertyNames.Name] = "Rezerviši let";
                    this.mUIRezervišiletButton.WindowTitles.Add("Lufthansa - Rezervacija leta");
                    #endregion
                }
                return this.mUIRezervišiletButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIRezervišiletButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIDistancaTxtWindow : WinWindow
    {
        
        public UIDistancaTxtWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "distancaTxt";
            this.WindowTitles.Add("Lufthansa - Rezervacija leta");
            #endregion
        }
        
        #region Properties
        public WinEdit UIDistancaTxtEdit
        {
            get
            {
                if ((this.mUIDistancaTxtEdit == null))
                {
                    this.mUIDistancaTxtEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIDistancaTxtEdit.WindowTitles.Add("Lufthansa - Rezervacija leta");
                    #endregion
                }
                return this.mUIDistancaTxtEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIDistancaTxtEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UICijenaTxtWindow : WinWindow
    {
        
        public UICijenaTxtWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "cijenaTxt";
            this.WindowTitles.Add("Lufthansa - Rezervacija leta");
            #endregion
        }
        
        #region Properties
        public WinEdit UICijenaTxtEdit
        {
            get
            {
                if ((this.mUICijenaTxtEdit == null))
                {
                    this.mUICijenaTxtEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUICijenaTxtEdit.WindowTitles.Add("Lufthansa - Rezervacija leta");
                    #endregion
                }
                return this.mUICijenaTxtEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUICijenaTxtEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "5";
            this.WindowTitles.Add("Lufthansa - Rezervacija leta");
            #endregion
        }
        
        #region Properties
        public WinClient UIPodacioletuClient
        {
            get
            {
                if ((this.mUIPodacioletuClient == null))
                {
                    this.mUIPodacioletuClient = new WinClient(this);
                    #region Search Criteria
                    this.mUIPodacioletuClient.WindowTitles.Add("Lufthansa - Rezervacija leta");
                    #endregion
                }
                return this.mUIPodacioletuClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIPodacioletuClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIPodacioletuGroup : WinGroup
    {
        
        public UIPodacioletuGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Podaci o letu";
            this.WindowTitles.Add("Lufthansa - Rezervacija leta");
            #endregion
        }
        
        #region Properties
        public WinWindow UIPrtljagTxtWindow
        {
            get
            {
                if ((this.mUIPrtljagTxtWindow == null))
                {
                    this.mUIPrtljagTxtWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUIPrtljagTxtWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUIPrtljagTxtWindow.SearchProperties[WinWindow.PropertyNames.Instance] = "3";
                    this.mUIPrtljagTxtWindow.WindowTitles.Add("Lufthansa - Rezervacija leta");
                    #endregion
                }
                return this.mUIPrtljagTxtWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUIPrtljagTxtWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIDataGridView1Window : WinWindow
    {
        
        public UIDataGridView1Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "dataGridView1";
            this.WindowTitles.Add("Lufthansa - Rezervacija leta");
            #endregion
        }
        
        #region Properties
        public UIDataGridViewTable UIDataGridViewTable
        {
            get
            {
                if ((this.mUIDataGridViewTable == null))
                {
                    this.mUIDataGridViewTable = new UIDataGridViewTable(this);
                }
                return this.mUIDataGridViewTable;
            }
        }
        #endregion
        
        #region Fields
        private UIDataGridViewTable mUIDataGridViewTable;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIDataGridViewTable : WinTable
    {
        
        public UIDataGridViewTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinTable.PropertyNames.Name] = "DataGridView";
            this.WindowTitles.Add("Lufthansa - Rezervacija leta");
            #endregion
        }
        
        #region Properties
        public UIRow0Row UIRow0Row
        {
            get
            {
                if ((this.mUIRow0Row == null))
                {
                    this.mUIRow0Row = new UIRow0Row(this);
                }
                return this.mUIRow0Row;
            }
        }
        
        public UIRow2Row UIRow2Row
        {
            get
            {
                if ((this.mUIRow2Row == null))
                {
                    this.mUIRow2Row = new UIRow2Row(this);
                }
                return this.mUIRow2Row;
            }
        }
        #endregion
        
        #region Fields
        private UIRow0Row mUIRow0Row;
        
        private UIRow2Row mUIRow2Row;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIRow0Row : WinRow
    {
        
        public UIRow0Row(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinRow.PropertyNames.Value] = "3;923;2;50;5;Imenko Prezimenko;0123456789123;38761123456;komentar";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Lufthansa - Rezervacija leta");
            #endregion
        }
        
        #region Properties
        public WinRowHeader UIItemRowHeader
        {
            get
            {
                if ((this.mUIItemRowHeader == null))
                {
                    this.mUIItemRowHeader = new WinRowHeader(this);
                    #region Search Criteria
                    this.mUIItemRowHeader.WindowTitles.Add("Lufthansa - Rezervacija leta");
                    #endregion
                }
                return this.mUIItemRowHeader;
            }
        }
        #endregion
        
        #region Fields
        private WinRowHeader mUIItemRowHeader;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIRow2Row : WinRow
    {
        
        public UIRow2Row(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(WinRow.PropertyNames.Value, ";2258;3;95;10;Djido Mova;0707977007007;38761007007;bez komentara", PropertyExpressionOperator.Contains));
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Lufthansa - Rezervacija leta");
            #endregion
        }
        
        #region Properties
        public WinCell UIDjidoMovaCell
        {
            get
            {
                if ((this.mUIDjidoMovaCell == null))
                {
                    this.mUIDjidoMovaCell = new WinCell(this);
                    #region Search Criteria
                    this.mUIDjidoMovaCell.SearchProperties[WinCell.PropertyNames.Value] = "Djido Mova";
                    this.mUIDjidoMovaCell.WindowTitles.Add("Lufthansa - Rezervacija leta");
                    #endregion
                }
                return this.mUIDjidoMovaCell;
            }
        }
        
        public WinCell UIItem38761007007Cell
        {
            get
            {
                if ((this.mUIItem38761007007Cell == null))
                {
                    this.mUIItem38761007007Cell = new WinCell(this);
                    #region Search Criteria
                    this.mUIItem38761007007Cell.SearchProperties[WinCell.PropertyNames.Value] = "38761007007";
                    this.mUIItem38761007007Cell.WindowTitles.Add("Lufthansa - Rezervacija leta");
                    #endregion
                }
                return this.mUIItem38761007007Cell;
            }
        }
        #endregion
        
        #region Fields
        private WinCell mUIDjidoMovaCell;
        
        private WinCell mUIItem38761007007Cell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIIzbrišiuneseniletWindow : WinWindow
    {
        
        public UIIzbrišiuneseniletWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "brisanjeBtn";
            this.WindowTitles.Add("Lufthansa - Rezervacija leta");
            #endregion
        }
        
        #region Properties
        public WinButton UIIzbrišiuneseniletButton
        {
            get
            {
                if ((this.mUIIzbrišiuneseniletButton == null))
                {
                    this.mUIIzbrišiuneseniletButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIIzbrišiuneseniletButton.SearchProperties[WinButton.PropertyNames.Name] = "Izbriši uneseni let";
                    this.mUIIzbrišiuneseniletButton.WindowTitles.Add("Lufthansa - Rezervacija leta");
                    #endregion
                }
                return this.mUIIzbrišiuneseniletButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIIzbrišiuneseniletButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIProvjeriteunesenepodWindow : WinWindow
    {
        
        public UIProvjeriteunesenepodWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = @"Provjerite unesene podatke za let i putnika! 
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Convert.ToInt32(String value)
   at AviokompanijaL.Form1.rezervacijaBtn_Click(Object sender, EventArgs e) in c:\Users\Merima\Desktop\PKKS-Zadaca1\pkksZadaca1\AviokompanijaL\Zadatak1\Form1.cs:line 107";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Static";
            this.WindowTitles.Add(@"Provjerite unesene podatke za let i putnika! 
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Convert.ToInt32(String value)
   at AviokompanijaL.Form1.rezervacijaBtn_Click(Object sender, EventArgs e) in c:\Users\Merima\Desktop\PKKS-Zadaca1\pkksZadaca1\AviokompanijaL\Zadatak1\Form1.cs:line 107");
            #endregion
        }
        
        #region Properties
        public WinText UIProvjeriteunesenepodText
        {
            get
            {
                if ((this.mUIProvjeriteunesenepodText == null))
                {
                    this.mUIProvjeriteunesenepodText = new WinText(this);
                    #region Search Criteria
                    this.mUIProvjeriteunesenepodText.SearchProperties[WinText.PropertyNames.Name] = @"Provjerite unesene podatke za let i putnika! System.FormatException: Input string was not in a correct format.   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer number, NumberFormatInfo info, Boolean parseDecimal)   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)   at System.Convert.ToInt32(String value)   at AviokompanijaL.Form1.rezervacijaBtn_Click(Object sender, EventArgs e) in c:\Users\Merima\Desktop\PKKS-Zadaca1\pkksZadaca1\AviokompanijaL\Zadatak1\Form1.cs:line 107";
                    this.mUIProvjeriteunesenepodText.WindowTitles.Add(@"Provjerite unesene podatke za let i putnika! 
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Convert.ToInt32(String value)
   at AviokompanijaL.Form1.rezervacijaBtn_Click(Object sender, EventArgs e) in c:\Users\Merima\Desktop\PKKS-Zadaca1\pkksZadaca1\AviokompanijaL\Zadatak1\Form1.cs:line 107");
                    #endregion
                }
                return this.mUIProvjeriteunesenepodText;
            }
        }
        #endregion
        
        #region Fields
        private WinText mUIProvjeriteunesenepodText;
        #endregion
    }
}
